# Generated by Django 5.2.8 on 2025-11-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('target_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('goals', models.TextField(blank=True)),
                ('time_zone', models.CharField(blank=True, max_length=100)),
                ('study_style', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
